version: '3'
services:
  neo4j:
    image: neo4j:5.17.0-enterprise
    volumes:
      - /$HOME/neo4j_latest_enterprise/logs:/logs
      - /$HOME/neo4j_latest_enterprise/config:/config
      - /$HOME/neo4j_latest_enterprise/data:/data
      - /$HOME/neo4j_latest_enterprise/plugins:/plugins
      - /$HOME/neo4j_latest_enterprise/import:/import
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_PLUGINS=["apoc", "graph-data-science", "bloom"]
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*,bloom.*,db.create.*,db.index.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*,gds.*,bloom.*,db.create.*,db.index.*
      - NEO4J_dbms_directories_import=/import
      - NEO4J_server_memory_heap_initial__size=1G
      - NEO4J_server_memory_heap_max__size=2G
      - NEO4J_server_memory_pagecache_size=1G
    ports:
      - "7474:7474"
      - "7473:7473"
      - "7687:7687"
    restart: always